### ISSUE TITLE
Can't create an order

### ISSUE THREAD

**Issue by MizarSG** [oleg6k/hitbtc-node-sdk#1]
Hi! i tried to create an order based on your examples, but i got an error.
My code: 

```
 const hitbtc = require('hitbtc-node-sdk');
 hitbtc.auth(APIKey, SecretKey);

/* or Market order */
orderParamsObject = {
    symbol: "ETHBTC",
    side: "sell",
    type: "market",
    quantity: 0.063

};

hitbtc.createNewOrder(orderParamsObject)
    .then(orderRequest => console.log(orderRequest))
    .catch(orderError => console.log(orderError));
```

Error:
querystring.js:43
  return str.replace(/[!'()*]/g, function (c) {
             ^

TypeError: str.replace is not a function

**Comment by oleg6k** [comment]
Hi! Thank you.
I guess the issue fixed. 
https://github.com/oleg6k/hitbtc-node-sdk/commit/3630c66c13697b00776b5db3004253a395d8c022
